version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    env_file:
        - .env
    ports:
        - "5438:5432"
  db:
    image: postgres
    restart: always
    network_mode: service:webapp
    environment:
        POSTGRES_USER: yourusername
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: yourdatabase
    volumes:
        - webapp_db_data:/var/lib/postgresql/data
volumes:
  webapp_db_data: 