version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    env_file:
        - .env
    networks:
      - example_platform
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: yourusername
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: yourdatabase
    volumes:
        - example_db_data:/var/lib/postgresql/data
    networks:
      - example_platform
    ports:
      - "5440:5432"
volumes:
  example_db_data: 

networks:
  example_platform:
    external: true